vmware/burp-rest-api

- .gitignore
- README.md
- src/main/java/com/vmware/burp/extension/service/BurpService.java
- src/main/java/com/vmware/burp/extension/web/BurpController.java
- src/main/resources/application.yml
Changes:
1. Add a `--burp.edition=[free|pro]` option (default to `pro`) that allows running with free edition jar, which refuses the --project-file cmd argument. (see issue #9)
2. Add a `/burp/reset` endpoint that replace current state with a clean state, effectively reset the workspace.
> Allow building & running with Burp free edition (limited capabilities)

- src/main/java/com/vmware/burp/extension/service/BurpService.java
A user reported that using burp-rest-api to Spider and Scan a site did not work. On investigation this is due to a subtlety of URL handling. If they Spider http://foo/ then the site map returns items with URLs http://foo:80/ and if they then scan http://foo/ this doesn't match the URLs like http://foo:80/
This pull request fixes that behavior.
> Make URL checks ignore default port specifications

- build.gradle
- src/main/java/com/vmware/burp/extension/domain/SpiderProgress.java
- src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java
- src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java
- src/main/java/com/vmware/burp/extension/service/BurpService.java
- src/main/java/com/vmware/burp/extension/web/BurpController.java
- src/main/resources/application.yml
This PR contains the following changes:
- Support for Burp _Scanner Passive_
- Experimental Support for _Spider Status_ (see https://github.com/vmware/burp-rest-api/issues/35)
Returns an estimate of the current status of the spider. Due to the current limitations in Burp's Extender API, this endpoint will return 100% whenever the spider is no longer discovering new resources
- Fixes/Improvements for _/burp/scanner/status_
> Passive Scan / Spider Status / Scan Status Fixes

- src/main/java/com/vmware/burp/extension/service/BurpService.java
Removed this check - why is it necessary? I found that this was causing issues scanning using SSL and a URL /subdirectory/ - i.e. initiating a scan on https://test.com/en:
url.toExternalForm() is **https://test.com:443/en/somepage**
baseUrl is **https://test.com/en**
url.toExternalForm().startsWith(baseUrl) is **false**
> Removing URL startWith check prior to scanning

- src/main/java/com/vmware/burp/extension/domain/Cookie.java
- src/main/java/com/vmware/burp/extension/domain/HttpMessage.java
- src/main/java/com/vmware/burp/extension/domain/Parameter.java
- src/main/java/com/vmware/burp/extension/domain/ParameterType.java
The site map model was inconsistent in terms of identifying a
particulare request, because the request's method was missing.
Also, other useful information that burp provides to its extensions was
not included.
To solve this, the following information was added to the site map model:
* request method
* request parameters
* response headers
* response cookies
For that purpose, the following properties including getters and
setters were added to the class HttpMessage:
* String method
* List<String> headers
* List<Cookie> cookies
* List<Parameter> parameters
The new classes Cookie and Parameter hold the values provided by the
burp interfaces ICookie and IParameter. The enum ParameterType holds the
static byte values of IParameter that represent the type of a parameter.
Resolves #43
> Improved sitemap model: method/param/header/cookie

- src/main/java/com/vmware/burp/extension/service/BurpService.java
Currently the scope method is simply getting URLs from the sitemap, and checking whether the baseUrl is within scope.
However, this is insufficient, due to the exceptions that may exist to the scope, such as certain paths or file extensions that are excluded (e.g. *.png, *.css, and so on).
Example:
Scope baseURL: http://example.org/
Exceptions: *.css and /criticalscriptthatdropsdatabases.cgi
Scanner will scan http://example.org/thisisatyle.css and http://example.org/criticalscriptthatdropsdatabases.cgi if they are in the sitemap (spider does not touch them, but lists them in the sitemap, although grayed out in the UI).
This PR checks for each URL in the sitemap if it is still within scope, and prevents those from being sent to the scanner (either active or passive) if it is not.
> Limit scanning to the scope

- src/main/java/com/vmware/burp/extension/service/BurpService.java
This should resolve the issue described by: #50 
Cause
---
Use of AND condition instead of OR condition means that user must be using a free Burp version AND have also not specified a project file.
However, this ignores two cases:
1. The user mistakenly states a project file with Burp free edition
2. The user does not state a project file with Burp paid edition
Both of these cases require the creation of an empty projectData array.
Resolution
---
Changed conditional operator from `&&` to `||`.
I also rearranged the operands so that the `Note:` line flows into the logic of the if-statement. 
"Burp Free does not support project..." => "`if (!burpEdition.equalsIgnoreCase('free')`"
> Fix for #50

- README.md
- build.gradle
- src/main/java/com/vmware/burp/extension/service/BurpService.java
- src/main/resources/application.yml
- src/test/java/com/vmware/burp/extension/client/BurpClientIT.java
As discussed with the original maintainers, I am deprecating the support for Burp Free / Burp Community.
Considering the exposed functionalities (see below), this extension has no use with Burp Free. Most of the operations are related to web scanning automation, which is not available in Burp Free/Community. 
Over the course of the past years, this option has created confusion between users as some people expected this extension to be able to fully operate with the Free edition.
> Deprecating support for Burp Free / Burp Community

- README.md
- build.gradle
- src/main/java/com/vmware/burp/extension/service/BurpService.java
Adds : 
- `-PappArgs="['arg1','arg2','arg3']"` to be able to pass arguments to burp suite directly via the gradle wrapper ( `gradlew bootRun -PappArgs="['--project-file=./test.burp','--config-file=./cfg.json','--user-config-file=./usr-cfg.json']"` ).
- Fixed #46 by changing what #52 introduced by changing the negative assertions to positive assertions and and making the logical operator back to `&&`
> Better Fix #50 and #46

- src/main/java/com/vmware/burp/extension/service/BurpService.java
Fix for #56 
Check if response is not null now includes active scan, too.
> Added check for existing response before scan

- README.md
- src/main/java/com/vmware/burp/extension/domain/HttpMessage.java
- src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java
- src/main/java/com/vmware/burp/extension/service/BurpService.java
- src/main/java/com/vmware/burp/extension/web/BurpController.java
- src/main/resources/application.yml
This PR is meant to resolve a bunch of standing issues, ahead of our major release bump.
In particular, the following changes have been made:
- Support for API address binding (by default, it's now binding on localhost only)
- _HttpMessage_ now returns the full HTTP request/response as base64. To reduce response size and overall response time, compression has been enabled by default for requests over 1024 bytes
- getConfigAsJson support for given configuration paths (e.g. 'proxy.request_listeners' to simply get the configuration regarding listeners)
> Bug fixes, and minor improvements ahead of major release bump

- .gitignore
- FAQ.md
- LICENSE
- README.md
- build.gradle
- src/entrypoint/java/burp/BurpExtender.java
- src/main/java/burp/LegacyBurpExtender.java
- src/main/java/com/vmware/burp/extension/domain/HttpMessage.java
- src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java
- src/main/java/com/vmware/burp/extension/service/BurpService.java
- src/main/java/com/vmware/burp/extension/utils/UserConfigUtils.java
- src/main/resources/application.yml
This changeset bumps the major version and implements the following 3 features:
1. burp-rest-api now loads the burp jar dinamically throgh the --burp.jar= flag.
2. burp-rest-api is loaded as a 2nd gen extension and is now possible to load
more than one extension at a time.
3. burp-rest-api can now loads burp 2nd gen extension through the --burp.ext=
flag.
In order to implement (2) we employed a classloading technique with a dummy
entrypoint _BurpExtender.java_ that loads the legacy burp
extension _LegacyBurpExtension.java_ after the full Burp Suite has been loaded
and launched _BurpService.java_.
**This work has been sponsored by Doyensec LLC** [![Doyensec](https://www.doyensec.com/images/logo.svg)](https://doyensec.com/)
> 2ndgen extensions

- src/entrypoint/java/burp/BurpExtender.java
On Linux the extensions are not loaded within a Thread that has the contextClassLoader not-null.
In order to find the correct contextClassLoader scan all the Threads in the JVM.
**This work has been sponsored by Doyensec LLC** [![Doyensec](https://www.doyensec.com/images/logo.svg)](https://doyensec.com/)
> Fix burp classloading on Linux

- README.md
The Java Version required by the project is actually Java x64 [here](https://support.portswigger.net/customer/portal/articles/1855756-burp-suite-software)and if we want to build this we're actually going to be needing JDK . I feel like the mention has to be made as I've seen/heard people trying to build this using JRE because burp suite works with just JREx64 but then they install JDK and problems happen .
> Java Version Clarification

- burp-rest-api.sh
Changed _burp-rest-api.sh_ to look for all required JARs despite their location within the app folder.
> Improved launcher script for Mac/Linux

- src/main/java/com/vmware/burp/extension/client/BurpClient.java
- src/main/java/com/vmware/burp/extension/domain/IssueConfidence.java
- src/main/java/com/vmware/burp/extension/domain/IssueSeverity.java
- src/main/java/com/vmware/burp/extension/service/BurpService.java
- src/main/java/com/vmware/burp/extension/utils/Utils.java
- src/main/java/com/vmware/burp/extension/web/BurpController.java
- src/test/java/com/vmware/burp/extension/client/BurpClientIT.java
@ikkisoft This adds the Severity, Confidence and Path filters in the `/burp/report` endpoint, as suggested in #125
> Add support for filtering report issues by severity/confidence/paths

- src/main/java/com/vmware/burp/extension/client/BurpClient.java
- src/main/java/com/vmware/burp/extension/domain/ScanProgress.java
- src/main/java/com/vmware/burp/extension/domain/ScanStatus.java
- src/main/java/com/vmware/burp/extension/domain/ScanStatusList.java
- src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java
- src/main/java/com/vmware/burp/extension/service/BurpService.java
- src/main/java/com/vmware/burp/extension/web/BurpController.java
- src/test/java/com/vmware/burp/extension/client/BurpClientIT.java
@ikkisoft This addresses the issue in #118 by retrieving a list of the scans and their corresponding statuses in the endpoint `/scanner/status`.
The scan percentage field has been removed from the response since the method `IScanQueueItem.getPercentageComplete()` is deprecated.
> Fix scan status issue

- src/main/java/com/vmware/burp/extension/client/BurpClient.java
- src/main/java/com/vmware/burp/extension/domain/ScanProgress.java
- src/main/java/com/vmware/burp/extension/domain/internal/ScanQueueMap.java
- src/main/java/com/vmware/burp/extension/service/BurpService.java
- src/main/java/com/vmware/burp/extension/web/BurpController.java
Addressing issue for Scan Status, this will add one more field to the response /burp/scanner/status, with scanStatus: "none" being default at start. scanPercentage is left untouched.
> Exposed Scan Status

- src/main/java/com/vmware/burp/extension/client/BurpClient.java
- src/main/java/com/vmware/burp/extension/web/BurpController.java
- src/test/java/com/vmware/burp/extension/client/BurpClientIT.java
This PR adds the feature requested in #139 
The new endpoint 
```
/proxy/history/partial
```
receives a ```from``` mandatory parameter and an optional ```to``` parameter to select the subset of the history requests.
> Add endpoint for partial history

- burp-rest-api.bat
- burp-rest-api.sh
Burp needts special JVM arguments when using java 17, see: https://forum.portswigger.net/thread/run-burp-on-openjdk-17-5611cb564e50e
> Java 17 compatibility

- src/main/java/com/vmware/burp/extension/domain/internal/SpiderQueueMap.java
- src/main/java/com/vmware/burp/extension/service/BurpService.java
- src/main/java/com/vmware/burp/extension/utils/Utils.java
- src/main/java/com/vmware/burp/extension/web/BurpController.java
Unlike [isInScope](https://portswigger.net/burp/extender/api/burp/IBurpExtenderCallbacks.html#isInScope-java.net.URL-), [getSiteMap](https://portswigger.net/burp/extender/api/burp/IBurpExtenderCallbacks.html#getSiteMap-java.lang.String-) works out of string URLs and does not remove the port if standard 80/443. 
This issue was probably affecting a few endpoints.
Testing:
* Executed the standard tests
* Attempted to reproduce #157 
Additional testing would be good.
> Fixing Issue #157 and probably others
